//Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
//By starting with 1 and 2, the first 10 terms will be:
//1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
//Design and implement an efficient algorithm that by considering the terms in the 
//Fibonacci sequence whose values do not exceed N, finds the sum of the even-valued terms.



#include "stdafx.h"
#include "stdafx.h"
#include <iostream>

using namespace std;

int main() {
    int userIn;
	int firstFib = 1;
	int secondFib = 1;
	int nextFib;
	int evenSum = 0; 

    cout << "Please enter the number of Fibonacci terms to find out the even sum : ";
    cin >> userIn;

    cout << "This is the Fibonacci series: " << firstFib << "  " << secondFib << "  ";
    for (int i = 1; i <= userIn; ++i) 
	{     
		nextFib = firstFib + secondFib;
        cout << nextFib << "  ";
        firstFib = secondFib;
        secondFib = nextFib;

		if (nextFib % 2 == 0)
		{
			evenSum = evenSum + nextFib;
		}
    }
	cout <<"\nThis is the even numbers sum: "<< evenSum <<endl;
	
	system("pause");
    return 0;
}